//상태 설명

const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export {USER_LOGIN_FAIL, USER_LOGIN_SUCCESS, USER_LOGIN_REQUEST}
